const String HomeRoute = "home";
const String LayoutRoute = "layout";
const String ProductsRoute = "products";
// const String UsersRoute = "users";
const String UserScreenRoute = "user_screen";
const String DriverRoute = "driver";
const String PazaheroRoute = "pazahero";
const String SellerRoute = "seller";
// const String OrdersRoute = "orders";
const String OrdersScreenRoute = "order_screen";//ito transaction
const String PazakayRoute = "pazakay";//ito transaction
const String PazshipRoute = "pazship";//ito transaction
const String PazabuyRoute = "pazabuy";//ito transaction
const String LoginRoute = "login";
const String RegistrationRoute = "registration";
const String CategoriesRoute = "categories";
const String BrandsRoute = "brands";
const String PageControllerRoute = "page";
